package org.exemple.demo.mon_appli.model;
// Generated 10 mai 2018 00:34:16 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Creneaux generated by hbm2java
 */
@Entity
@Table(name = "creneaux")
public class Creneaux implements java.io.Serializable {

	private Long id;
	private int version;
	private Medecins medecins;
	private int mdebut;
	private int hfin;
	private int hdebut;
	private int mfin;
	private Set<Rv> rvs = new HashSet<Rv>(0);

	public Creneaux() {
	}

	public Creneaux(Medecins medecins, int mdebut, int hfin, int hdebut, int mfin) {
		this.medecins = medecins;
		this.mdebut = mdebut;
		this.hfin = hfin;
		this.hdebut = hdebut;
		this.mfin = mfin;
	}

	public Creneaux(Medecins medecins, int mdebut, int hfin, int hdebut, int mfin, Set<Rv> rvs) {
		this.medecins = medecins;
		this.mdebut = mdebut;
		this.hfin = hfin;
		this.hdebut = hdebut;
		this.mfin = mfin;
		this.rvs = rvs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MEDECIN", nullable = false)
	public Medecins getMedecins() {
		return this.medecins;
	}

	public void setMedecins(Medecins medecins) {
		this.medecins = medecins;
	}

	@Column(name = "MDEBUT", nullable = false)
	public int getMdebut() {
		return this.mdebut;
	}

	public void setMdebut(int mdebut) {
		this.mdebut = mdebut;
	}

	@Column(name = "HFIN", nullable = false)
	public int getHfin() {
		return this.hfin;
	}

	public void setHfin(int hfin) {
		this.hfin = hfin;
	}

	@Column(name = "HDEBUT", nullable = false)
	public int getHdebut() {
		return this.hdebut;
	}

	public void setHdebut(int hdebut) {
		this.hdebut = hdebut;
	}

	@Column(name = "MFIN", nullable = false)
	public int getMfin() {
		return this.mfin;
	}

	public void setMfin(int mfin) {
		this.mfin = mfin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "creneaux")
	public Set<Rv> getRvs() {
		return this.rvs;
	}

	public void setRvs(Set<Rv> rvs) {
		this.rvs = rvs;
	}

}
