package org.exemple.demo.mon_appli.model;
// Generated 10 mai 2018 00:34:16 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Medecins generated by hbm2java
 */
@Entity
@Table(name = "medecins")
public class Medecins implements java.io.Serializable {

	private Long id;
	private int version;
	private String titre;
	private String nom;
	private String prenom;
	private Set<Creneaux> creneauxes = new HashSet<Creneaux>(0);

	public Medecins() {
	}

	public Medecins(String titre, String nom, String prenom) {
		this.titre = titre;
		this.nom = nom;
		this.prenom = prenom;
	}

	public Medecins(String titre, String nom, String prenom, Set<Creneaux> creneauxes) {
		this.titre = titre;
		this.nom = nom;
		this.prenom = prenom;
		this.creneauxes = creneauxes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "TITRE", nullable = false, length = 5)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medecins")
	public Set<Creneaux> getCreneauxes() {
		return this.creneauxes;
	}

	public void setCreneauxes(Set<Creneaux> creneauxes) {
		this.creneauxes = creneauxes;
	}

}
