package org.exemple.demo.mon_appli.model;
// Generated 10 mai 2018 00:34:16 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Rv generated by hbm2java
 */
@Entity
@Table(name = "rv", uniqueConstraints = @UniqueConstraint(columnNames = { "JOUR",
		"ID_CRENEAU" }))
public class Rv implements java.io.Serializable {

	private Long id;
	private Clients clients;
	private Creneaux creneaux;
	private Date jour;

	public Rv() {
	}

	public Rv(Clients clients, Creneaux creneaux, Date jour) {
		this.clients = clients;
		this.creneaux = creneaux;
		this.jour = jour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENT", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CRENEAU", nullable = false)
	public Creneaux getCreneaux() {
		return this.creneaux;
	}

	public void setCreneaux(Creneaux creneaux) {
		this.creneaux = creneaux;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "JOUR", nullable = false, length = 10)
	public Date getJour() {
		return this.jour;
	}

	public void setJour(Date jour) {
		this.jour = jour;
	}

}
